### PR TITLE
fix(cache): ensure LoadingOnceCache can only load once

### LINKED ISSUE #3748: TestLoadingOnceCache is flaky
```console
$ go test -v ./pkg/cache -run TestLoadingOnceCache -count=10 -race
=== RUN   TestLoadingOnceCache
--- PASS: TestLoadingOnceCache (0.00s)
=== RUN   TestLoadingOnceCache
--- PASS: TestLoadingOnceCache (0.00s)
=== RUN   TestLoadingOnceCache
--- PASS: TestLoadingOnceCache (0.00s)
=== RUN   TestLoadingOnceCache
--- PASS: TestLoadingOnceCache (0.00s)
=== RUN   TestLoadingOnceCache
--- PASS: TestLoadingOnceCache (0.00s)
=== RUN   TestLoadingOnceCache
--- PASS: TestLoadingOnceCache (0.00s)
=== RUN   TestLoadingOnceCache
    loading_test.go:47:
                Error Trace:    /home/maxime/Documents/github.com/maxbrunet/parca/pkg/cache/loading_test.go:47
                Error:          Not equal:
                                expected: 0x1
                                actual  : 0x3
                Test:           TestLoadingOnceCache
--- FAIL: TestLoadingOnceCache (0.00s)
=== RUN   TestLoadingOnceCache
--- PASS: TestLoadingOnceCache (0.00s)
=== RUN   TestLoadingOnceCache
    loading_test.go:47:
                Error Trace:    /home/maxime/Documents/github.com/maxbrunet/parca/pkg/cache/loading_test.go:47
                Error:          Not equal:
                                expected: 0x1
                                actual  : 0x2
                Test:           TestLoadingOnceCache
--- FAIL: TestLoadingOnceCache (0.00s)
=== RUN   TestLoadingOnceCache
    loading_test.go:47:
                Error Trace:    /home/maxime/Documents/github.com/maxbrunet/parca/pkg/cache/loading_test.go:47
                Error:          Not equal:
                                expected: 0x1
                                actual  : 0x2
                Test:           TestLoadingOnceCache
--- FAIL: TestLoadingOnceCache (0.00s)
FAIL
FAIL    github.com/parca-dev/parca/pkg/cache    0.025s
FAIL
```

My guess:

The singleflight group ensure no concurrent calls to loader happen:

https://github.com/parca-dev/parca/blob/f1f7e8aba381cf6638cbb43f3e04ccf440a7ed77/pkg/cache/loading.go#L111-L113

But it sometimes happens for loader to be called once or more **sequentially** by concurrent go routines between these two lines:

https://github.com/parca-dev/parca/blob/f1f7e8aba381cf6638cbb43f3e04ccf440a7ed77/pkg/cache/loading.go#L80-L85

Likely the key should be added within the loader before it returns.

### PR DESCRIPTION
**Pull request by maxbrunet**
The entire "get or load" operation must be in the single-flight group to ensure loading can only happen once.

This is a minimal change that does not break or extend the API.

Fixes #3748

### CODE REVIEW

File: pkg/cache/loading.go [hunk 1]
```diff
@@ -29,6 +29,8 @@ type LoadingLRUCacheWithTTL[K comparable, V any] struct {
 	lru    *LRUCacheWithTTL[K, V]
 	loader LoaderFunc[K, V]
 	closer func() error
+
+	sfg *singleflight.Group
```
Comment (kakkoyun) [inline pkg/cache/loading.go:33]: Why don't we create a new struct for `LoadingOnceCache` and put the singleflight there? It would be easier to reason about. We can embed the `LoadingLRUCacheWithTTL` into that struct and override the `Get` method. What do you think?

**Review by kakkoyun — COMMENTED** [review]
Thanks for taking care of this. I have a small suggestion.

File: pkg/cache/loading.go (hunk 1 above)
Comment (maxbrunet) [reply pkg/cache/loading.go]: Made the changes to do that, let me know what you think :)

**Review by kakkoyun — APPROVED** [review]
LGTM
