### PR TITLE
parse labels only if labels exist

### LINKED ISSUE #2680: Comparing two profile causes a crash on the UI
This is currently happening on the `main` branch.

To recreate this:
1. Start the Parca frontend locally.
2. click "compare"
3. click the right "search" (if you click the left "search" first, it works)

image

### PR DESCRIPTION
**Pull request by monicawoj**
resolves #2680

### CODE REVIEW

**Comment by brancz** [comment]
Looks good, but there is a linter that doesn't seem happy.

File: ui/packages/shared/profile/src/ProfileSource.tsx [hunk 1]
```diff
@@ -82,12 +82,17 @@ export function ProfileSelectionFromParams(
   ) {
     // TODO: Refactor parsing the query and adding matchers
     let query = Query.parse(expression);
-    ParseLabels(labels ?? ['']).forEach(l => {
-      const [newQuery, changed] = query.setMatcher(l.name, l.value);
-      if (changed) {
-        query = newQuery;
-      }
-    });
+    if (labels) {
```
Comment (yomete) [inline ui/packages/shared/profile/src/ProfileSource.tsx:85]: An `!== undefined` check should make the linter here

**Review by yomete — APPROVED** [review]
Thanks for the fix! 🚢🇮🇹
