### PR TITLE
go.mod: Upgrade parquet-go and arcticdb

### LINKED ISSUE #1062: SIGKILL after a few seconds when CPU doesn't support AVX instructions
I've been running a small parca instance (it is awesome 🎉). Today I updated to the latest version (0.11.1):

```
$ ./parca --version
parca, version 0.11.1 (commit: fcbc4371da7ec149d58b7cd1e39c782a1bccd595)
```

After the update parca starts successfully but it dies after a few seconds with:

```
SIGILL: illegal instruction
PC=0x9bb34f m=11 sigcode=2
instruction bytes: 0xc4 0xe2 0x7d 0x58 0x4c 0x24 0x20 0x48 0xc1 0xe9 0x20 0x48 0xf 0xaf 0xcb 0x48

goroutine 141 [running]:
github.com/segmentio/parquet-go/bloom.filterInsert({0xc007711e40, 0x1, 0x1}, 0x418fb529e8aa5d)
	github.com/segmentio/parquet-go@v0.0.0-20220421002521-93f8e5ed3407/bloom/filter_amd64.s:110 +0xf fp=0xc009845400 sp=0xc0098453f8 pc=0x9bb34f
github.com/segmentio/parquet-go/bloom.SplitBlockFilter.Insert(...)
	github.com/segmentio/parquet-go@v0.0.0-20220421002521-93f8e5ed3407/bloom/filter.go:62
github.com/segmentio/parquet-go/bloom.(*SplitBlockFilter).Insert(0x203000?, 0xc007ff8600?)
	<autogenerated>:1 +0x48 fp=0xc009845430 sp=0xc009845400 pc=0x9bb628
github.com/segmentio/parquet-go.(*bloomFilterEncoder).insert(0xc00108a480, {0xc007ff8600?, 0x7f164bbe1c80?, 0x42?})
	github.com/segmentio/parquet-go@v0.0.0-20220421002521-93f8e5ed3407/bloom.go:200 +0x47 fp=0xc009845460 sp=0xc009845430 pc=0xab5967
github.com/segmentio/parquet-go.(*bloomFilterEncoder).EncodeByteArray.func1({0xc007ff8600?, 0x480?, 0x18?})
	github.com/segmentio/parquet-go@v0.0.0-20220421002521-93f8e5ed3407/bloom.go:183 +0x2e fp=0xc009845490 sp=0xc009845460 pc=0xab572e
github.com/segmentio/parquet-go/encoding.(*ByteArrayList).Range(0xc009845508, 0xc0098454e0)
	github.com/segmentio/parquet-go@v0.0.0-20220421002521-93f8e5ed3407/encoding/bytearray.go:121 +0x97 fp=0xc0098454d0 sp=0xc009845490 pc=0x9bebb7
github.com/segmentio/parquet-go.(*bloomFilterEncoder).EncodeByteArray(0x40da27?, {{0xc007ff8000, 0x1, 0xba}, {0xc007ff8600, 0x36, 0x5d0}})
	github.com/segmentio/parquet-go@v0.0.0-20220421002521-93f8e5ed3407/bloom.go:183 +0x58 fp=0xc009845500 sp=0xc0098454d0 pc=0xab5698
github.com/segmentio/parquet-go.(*byteArrayPage).WriteTo(0xc001159800?, {0x3fa2a10?, 0xc00108a480?})
	github.com/segmentio/parquet-go@v0.0.0-20220421002521-93f8e5ed3407/page.go:652 +0x6e fp=0xc009845578 sp=0xc009845500 pc=0xadce4e
github.com/segmentio/parquet-go.(*writerColumn).flushFilterPages(0xc001159800)
	github.com/segmentio/parquet-go@v0.0.0-20220421002521-93f8e5ed3407/writer.go:789 +0xed fp=0xc0098455c0 sp=0xc009845578 pc=0xafd2cd
github.com/segmentio/parquet-go.(*writer).writeRowGroup(0xc000605d40, 0xc00a339e00?, {0x0, 0x0, 0x0})
	github.com/segmentio/parquet-go@v0.0.0-20220421002521-93f8e5ed3407/writer.go:527 +0x208 fp=0xc009845888 sp=0xc0098455c0 pc=0xafba28
github.com/segmentio/parquet-go.(*writer).flush(...)
	github.com/segmentio/parquet-go@v0.0.0-20220421002521-93f8e5ed3407/writer.go:418
github.com/segmentio/parquet-go.(*writer).close(0xc000605d40)
	github.com/segmentio/parquet-go@v0.0.0-20220421002521-93f8e5ed3407/writer.go:411 +0x7d fp=0xc0098458f0 sp=0xc009845888 pc=0xafae9d
github.com/segmentio/parquet-go.(*Writer).Close(...)
	github.com/segmentio/parquet-go@v0.0.0-20220421002521-93f8e5ed3407/writer.go:94
github.com/polarsignals/arcticdb/dynparquet.(*Schema).SerializeBuffer(0xc008eebff9?, 0xc0092cd760)
	github.com/polarsignals/arcticdb@v0.0.0-20220428085204-3fca71a931b1/dynparquet/schema.go:395 +0x25b fp=0xc0098459b0 sp=0xc0098458f0 pc=0xb4a01b
github.com/polarsignals/arcticdb.(*Table).InsertBuffer(0xc00070f840, 0xc000d71770?)
	github.com/polarsignals/arcticdb@v0.0.0-20220428085204-3fca71a931b1/table.go:174 +0x2c fp=0xc0098459f8 sp=0xc0098459b0 pc=0xca876c
github.com/parca-dev/parca/pkg/parcacol.InsertProfileIntoTable({0x3f8d988?, 0xc00901dd70?}, {0x3f675c0, 0xc000d71770}, {0x3f76ea0, 0xc00070f840}, {0xc00a00f620, 0x3, 0x3}, 0xc00a339c20)
	github.com/parca-dev/parca/pkg/parcacol/parcacol.go:45 +0xc2 fp=0xc009845a40 sp=0xc0098459f8 pc=0x28d8f82
github.com/parca-dev/parca/pkg/profilestore.(*ProfileColumnStore).WriteRaw(0xc0012960c0, {0x3f8d8e0?, 0xc0007d8200?}, 0xc00a00f5c0)
	github.com/parca-dev/parca/pkg/profilestore/profilecolumnstore.go:126 +0xcb9 fp=0xc009845cc0 sp=0xc009845a40 pc=0x28def19
github.com/parca-dev/parca/pkg/scrape.(*scrapeLoop).run(0xc000db9860, 0x0?, 0x0?, 0x0)
	github.com/parca-dev/parca/pkg/scrape/scrape.go:484 +0xe9f fp=0xc009845fb0 sp=0xc009845cc0 pc=0x290ba1f
github.com/parca-dev/parca/pkg/scrape.(*scrapePool).sync.func3()
	github.com/parca-dev/parca/pkg/scrape/scrape.go:261 +0x35 fp=0xc009845fe0 sp=0xc009845fb0 pc=0x2909d95
runtime.goexit()
	runtime/asm_amd64.s:1571 +0x1 fp=0xc009845fe8 sp=0xc009845fe0 pc=0x46b421
created by github.com/parca-dev/parca/pkg/scrape.(*scrapePool).sync
	github.com/parca-dev/parca/pkg/scrape/scrape.go:261 +0x3bc

...
```

[Full stack trace (a bit verbose)](https://gist.github.com/jorgelbg/0ba6339bf4bb38029ac00ec931d880eb)

The host where I was running parca does not have support for AVX instructions (which is used by `parquet-go`):

```
$ grep avx /proc/cpuinfo
<empty>
```

`lscpu` output:

```
$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                24
On-line CPU(s) list:   0-23
Thread(s) per core:    2
Core(s) per socket:    6
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 44
Model name:            Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz
Stepping:              2
CPU MHz:               1693.310
CPU max MHz:           2933.0000
CPU min MHz:           1600.0000
BogoMIPS:              5867.00
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              12288K
NUMA node0 CPU(s):     0,2,4,6,8,10,12,14,16,18,20,22
NUMA node1 CPU(s):     1,3,5,7,9,11,13,15,17,19,21,23
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 popcnt aes lahf_lm epb ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid dtherm ida arat
```

I get why it fails but I feel that either a check/validation is missing in `parquet-go` itself or in a higher level (arcticdb/parca).

### PR DESCRIPTION
**Pull request by brancz**
Fixes #1062 

(also thanks to passing context everywhere shutdown of Parca is now waaaaaay faster 🎉 )

### CODE REVIEW

File: pkg/parcacol/parcacol.go [hunk 1]
```diff
@@ -42,7 +42,7 @@ func InsertProfileIntoTable(ctx context.Context, logger log.Logger, table Table,
 		return 0, err
 	}
 
-	_, err = table.InsertBuffer(buf)
+	_, err = table.InsertBuffer(ctx, buf)
```
Comment (metalmatze) [inline pkg/parcacol/parcacol.go:45]: Nice. In one of my branches I already added a TODO there. :tada:

**Review by metalmatze — APPROVED** [review]
