### PR TITLE
pkg/query: Fix adding a unit to the flamegraph

### LINKED ISSUE #578: Broken cumulative value formatting in profile popup
It seems that for some reason our formatting of cumulative values in the popup is broken.

Screenshot from 2022-01-25 18-54-09

It's probably some wiring in this package: https://github.com/parca-dev/parca/tree/main/ui/packages/shared/profile

### PR DESCRIPTION
**Pull request by metalmatze**
Fixes #578

For some reason, we didn't set the unit field anymore. :man_shrugging: 
It might be easier to construct the struct in the workflow I chose now and similar mistakes could be easier to catch. Either way, I added updated a unit test too to catch it in the future.

### CODE REVIEW

File: pkg/query/flamegraph_flat.go [hunk 1]
```diff
@@ -116,12 +116,16 @@ func GenerateFlamegraphFlat(ctx context.Context, tracer trace.Tracer, metaStore
...
-	flamegraph.Root.Diff = rootNode.Diff
-	flamegraph.Root.Children = rootNode.Children
+	flamegraph := &pb.Flamegraph{
+		Root: &pb.FlamegraphRootNode{
+			Cumulative: rootNode.Cumulative,
+			Diff:       rootNode.Diff,
+			Children:   rootNode.Children,
+		},
+		Total:  rootNode.Cumulative,
+		Unit:   p.ProfileMeta().SampleType.Unit,
```
Comment (metalmatze) [inline pkg/query/flamegraph_flat.go:126]: This line was missing before.

**Comment by metalmatze** [comment]
The CI errors are related to https://github.com/parca-dev/parca/issues/499 
Merging here and then finally trying to fix that flaky test.
